version: '3'

services:
  app:
    build: 
      context: node
    tty: true
    container_name: app
    entrypoint: wait-for db:3306 -t 40 -- docker-entrypoint.sh
    volumes:
      - ./node:/usr/src/app
    networks:
      - node-network
    ports:
      - "3000:3000"
    depends_on:
      - db
    
    

  db: 
    platform: linux/x86_64
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

networks:
  node-network:
    driver: bridge